import 'package:practice1/api/ApiCient.dart';
import 'package:practice1/model/product_model.dart';

class ApiProvider {
  ApiProvider._();

  static void getProduct(Function(List<Product>? list) onResponse) {
    ApiClient.call(
      ApiClient.product,
      isDebug: true,
      onResponse: (body) {
        Autogenerated model = Autogenerated.fromJson(body);

        onResponse(model.products);
      },
    );
  }
}
